-- MySQL Script generated by MySQL Workbench
-- Mon Mar 15 14:44:56 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`DEPARTMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DEPARTMENT` (
  `Dep_Num` INT NOT NULL,
  `Name` VARCHAR(20) NULL,
  PRIMARY KEY (`Dep_Num`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROFESSOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROFESSOR` (
  `id` INT NOT NULL,
  `FName` VARCHAR(15) NULL,
  `LName` VARCHAR(15) NULL,
  `DepNo` INT NULL,
  `Type` INT NULL,
  `Prof_Type` VARCHAR(6) NULL,
  `PROFESSORcol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `DepNo_idx` (`DepNo` ASC) VISIBLE,
  CONSTRAINT `DepNo`
    FOREIGN KEY (`DepNo`)
    REFERENCES `mydb`.`DEPARTMENT` (`Dep_Num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ROOM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ROOM` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Building` VARCHAR(15) NULL,
  `Number` VARCHAR(10) NULL,
  `Capacity` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLASS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLASS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Cat_Num` INT NULL,
  `Name` VARCHAR(20) NULL,
  `Size` INT NULL,
  `Dept` INT NULL,
  `Room` INT NULL,
  `Instructor` INT NULL,
  `ClassStart` TIMESTAMP NULL,
  `Class End` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `Dep_No_idx` (`Dept` ASC) VISIBLE,
  INDEX `FK_RoomID_idx` (`Room` ASC) VISIBLE,
  INDEX `FK_Instructor_idx` (`Instructor` ASC) VISIBLE,
  CONSTRAINT `FK_Dep_No`
    FOREIGN KEY (`Dept`)
    REFERENCES `mydb`.`DEPARTMENT` (`Dep_Num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_RoomID`
    FOREIGN KEY (`Room`)
    REFERENCES `mydb`.`ROOM` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Instructor`
    FOREIGN KEY (`Instructor`)
    REFERENCES `mydb`.`PROFESSOR` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROF_PREFERENCES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROF_PREFERENCES` (
  `ProfID` INT NOT NULL,
  `Pref_Type` VARCHAR(6) NOT NULL,
  `Start` TIMESTAMP NOT NULL,
  `End` TIMESTAMP NOT NULL,
  INDEX `ProfID_idx` (`ProfID` ASC) VISIBLE,
  CONSTRAINT `ProfID`
    FOREIGN KEY (`ProfID`)
    REFERENCES `mydb`.`PROFESSOR` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
